title: Análisis de Puntaje Global de Pruebas Saber 11 en el periodo comprendido de 2014-1 a 2022-2
author: Aza Daniel, Díaz Nataly, Estupiñán Juan, Rocha Juan, Rodríguez Silvana
logo: assets/logo_2.png

launch_buttons:
  binderhub_url: "https://mybinder.org"
  thebe: true

latex:
  commands:
    latexmk: {}

execute:
  execute_notebooks: "off"

repository:
  url: https://github.com/Juanpablor5/analitica_saber-11.old
  path_to_book: docs  # Optional path to your book, relative to the repository root
  branch: main

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true